/*  Copyright 2020 Google LLC

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License. */

/* This file tests functions generated by codegen_gen_test.cpp.
   Every function here of the form run*Test() has a corresponding
   function in codegen_gen_test.cpp named generate*Test().
*/

#include "codegen_generated.h"
#include "codegen_test_util.h"

#include <string>
#include <utility>
#include "runtime/diags_test_util.h"
#include "runtime/util.h"
using oalex::assertEqual;
using oalex::Bug;
using oalex::InputDiags;
using oalex::JsonLoc;
using oalex::test::assertJsonLocIsString;
using std::pair;
using std::string;
using std::tuple;

namespace {

void runSingleStringTest() {
  string msg = "hello";
  auto ctx = testInputDiags(msg);
  ssize_t pos = 0;
  JsonLoc jsloc = parseHelloKeyword(ctx, pos);

  assertJsonLocIsString(__func__, jsloc, msg, 0, msg.size());

  msg = "goodbye";
  ctx = testInputDiags(msg);
  pos = 0;
  jsloc = parseHelloKeyword(ctx, pos);
  if(!jsloc.holdsError()) BugMe("Was expecting string match to fail");
}

void runSingleRegexTest() {
  const tuple<string, JsonLoc(*)(InputDiags&, ssize_t&), size_t> inputs[] = {
    {"fox", parseFooOrFox, 3},
    {"foood", parseLongFood, 5},
    {"abcde", parseAbcXyz, 3},
    {"xyyyz", parseAbcXyz, 5},
    {"abc", parseAbcWholeLine, 3},
    {"abc+", parseAbcWord, 3},
  };
  for(auto& [msg, parseMsg, len] : inputs) {
    auto ctx = testInputDiags(msg);
    ssize_t pos = 0;
    JsonLoc jsloc = parseMsg(ctx, pos);
    assertJsonLocIsString(__func__, jsloc, string(msg, 0, len), 0, len);
  }


  const pair<string, JsonLoc(*)(InputDiags&, ssize_t&)> bad_inputs[] = {
    {"fort", parseFooOrFox},
    {"fod", parseFooOrFox},
    {"abxyz", parseAbcXyz},
    {"abcd", parseAbcWholeLine},
    {"abc+", parseAbcWholeLine},
  };
  for(auto& [msg, parseMsg] : bad_inputs) {
    auto ctx = testInputDiags(msg);
    ssize_t pos = 0;
    JsonLoc jsloc = parseFooOrFox(ctx, pos);
    if(!jsloc.holdsError()) BugMe("Was expecting regex match to fail");
  }
}

void runConcatTest() {
  auto ctx = testInputDiags("int x = 5;  // A declaration");
  ssize_t pos = 0;
  JsonLoc jsloc = parseDefinition(ctx, pos);
  string expected = R"({
    id: "x",
    value: "5"
  })";
  if(jsloc.holdsError()) BugMe("parseDefinition() failed");
  assertEqual(__func__, expected, jsloc.prettyPrint(2));

  ctx = testInputDiags("intx = 5;");
  pos = 0;
  jsloc = parseAssignment(ctx, pos);
  if(!jsloc.holdsError()) BugMe("run-on word matched unexpectedly");

  ctx = testInputDiags("y=x;");
  pos = 0;
  jsloc = parseAssignment(ctx, pos);
  expected = R"({
    lhs: "y",
    rhs: "x"
  })";
  if(jsloc.holdsError()) BugMe("parseAssignment() failed");
  assertEqual(__func__, expected, jsloc.prettyPrint(2));
}

}  // namespace

int main() {
  if(!goodFunc()) Bug("goodFunc() returned false");
  if(badFunc()) Bug("badFunc() returned true");

  auto ctx = testInputDiags("x = 5;");
  size_t pos = 0;
  JsonLoc res = parseAsgnStmt(ctx, pos);
  if(!res.holdsError())
    Bug("parseAsgn() returning success, but is unimplemented!");

  runSingleStringTest();
  runSingleRegexTest();
  runConcatTest();
}
